# Generated by Django 5.0 on 2024-01-06 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('gender', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('I', 'Não definido')], max_length=1)),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='data de nascimento')),
                ('city', models.CharField(default='Teresina', max_length=64)),
                ('district', models.CharField(default='Real Copagri', max_length=64)),
                ('contact', models.CharField(blank=True, max_length=16, null=True)),
                ('email', models.EmailField(blank=True, max_length=64, null=True)),
                ('registration_date', models.DateField(auto_now=True, verbose_name='data do cadastro')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='cliente_fotos')),
                ('cpf', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='CPF')),
                ('last_purchase_date', models.DateTimeField(null=True, verbose_name='data da última compra')),
                ('status', models.CharField(choices=[('1', 'Em dia'), ('2', 'Mensal'), ('3', 'Devedor')], default='3', max_length=1)),
            ],
        ),
    ]
