# Generated by Django 5.0 on 2024-01-08 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(default='Teresina', max_length=64, verbose_name='cidade'),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='contato'),
        ),
        migrations.AlterField(
            model_name='client',
            name='district',
            field=models.CharField(default='Real Copagri', max_length=64, verbose_name='bairro'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=64, null=True, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('I', 'Não definido')], max_length=1, verbose_name='sexo'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=256, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='client',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='cliente_fotos', verbose_name='foto'),
        ),
    ]
