# Generated by Django 5.0 on 2024-01-06 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_produto_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'produto'},
        ),
    ]
