# Generated by Django 5.0 on 2024-01-05 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_hierarchy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='nome')),
                ('login', models.CharField(max_length=16, unique=True)),
                ('admission_date', models.DateField()),
                ('desk_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_hierarchy.desk')),
                ('sector_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_hierarchy.sector')),
            ],
        ),
    ]
