# Generated by Django 5.0 on 2024-01-06 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'empregado'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='admission_date',
            field=models.DateField(verbose_name='data de admissão'),
        ),
    ]
