# Generated by Django 4.2.7 on 2023-12-03 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=32, unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=64, unique=True, verbose_name='Nome')),
                ('fabricante', models.CharField(max_length=64, null=True, verbose_name='Fabricante')),
                ('peso_bruto', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Peso bruto')),
                ('unidade_peso', models.CharField(max_length=3, null=True, verbose_name='Unidade')),
                ('descricao', models.CharField(max_length=128, null=True, verbose_name='Descrição')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço')),
                ('data_cadastro', models.DateField(auto_now_add=True, verbose_name='Data do cadastro')),
                ('data_fabricacao', models.DateField(null=True, verbose_name='Data de fabricação')),
                ('unidade_medida', models.CharField(max_length=2, null=True, verbose_name='Unidade de medida')),
            ],
        ),
    ]
