# Generated by Django 5.0 on 2023-12-31 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=256)),
                ('sexo', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('I', 'Não definido')], max_length=1)),
                ('data_nascimento', models.DateField(null=True, verbose_name='data de nascimento')),
                ('cidade', models.CharField(default='Teresina', max_length=64)),
                ('bairro', models.CharField(default='Real Copagri', max_length=64)),
                ('fone', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=64)),
                ('data_cadastro', models.DateField(auto_now=True)),
            ],
        ),
    ]
