# Generated by Django 5.0 on 2024-01-01 01:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_alter_cliente_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='fone',
            new_name='contato',
        ),
        migrations.AddField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='data_ultima_compra',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='data da última compra'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='status',
            field=models.CharField(choices=[('1', 'Vermelho'), ('2', 'Amarelho'), ('3', 'Verde')], default='3', max_length=1),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='data_cadastro',
            field=models.DateField(auto_now=True, verbose_name='data do cadastro'),
        ),
    ]
