# Generated by Django 5.0 on 2024-01-02 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_alter_cliente_data_ultima_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='status',
            field=models.CharField(choices=[('1', 'Em dia'), ('2', 'Mensal'), ('3', 'Devedor')], default='3', max_length=1),
        ),
    ]
