# Generated by Django 5.0 on 2024-01-06 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_alter_produto_options_alter_produto_descricao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
