# Generated by Django 5.0 on 2024-01-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desk_city', models.CharField(max_length=128, unique=True, verbose_name='escritório')),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='nome')),
                ('acronym', models.CharField(max_length=8, unique=True, verbose_name='sigla')),
                ('service', models.TextField(max_length=512, verbose_name='descrição do serviço')),
                ('create_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
