# Generated by Django 5.0 on 2024-01-06 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_hierarchy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='desk',
            options={'verbose_name': 'escritório'},
        ),
        migrations.AlterModelOptions(
            name='sector',
            options={'verbose_name': 'setor', 'verbose_name_plural': 'setores'},
        ),
    ]
